apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/da25m531/assignment3/mlops-pytorch-pipeline/data
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkpoint-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/da25m531/assignment3/mlops-pytorch-pipeline/checkpoints
    type: DirectoryOrCreate
