apiVersion: batch/v1
kind: Job
metadata:
  name: mlops-training-job-gpu
spec:
  backoffLimit: 0
  template:
    spec:
      nodeSelector:
        accelerator: nvidia-gpu
      containers:
      - name: training
        image: mlops-train:v1
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: config-volume
          mountPath: /app/configs/training_config.yaml
          subPath: training_config.yaml
        - name: data-volume
          mountPath: /app/data
        - name: checkpoint-volume
          mountPath: /app/checkpoints
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: training-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: checkpoint-volume
        persistentVolumeClaim:
          claimName: checkpoint-pvc
